version: '3.7'

#Service
services: 
  #Nginx Serivce
  nginx:
    image: nginx:1.17
    ports: 
      - 80:80
    volumes:
      - ./src:/var/www/php:ro
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - php
  
  #PHP Service
  php:
    build: ./.docker/php
    working_dir: /var/www/php
    volumes: 
      - ./src:/var/www/php
    depends_on: 
      - mysql
  
  #MySQL Serice
  mysql:
    image: mysql:8
    environment: 
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: demo
    volumes: 
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - mysqldata:/var/lib/mysql
#Volumes
volumes:

  mysqldata: